<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getAcls</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nQnVmZmVyIGJ1ZmZlciA9IG5ldyBTdHJpbmdCdWZmZXIoKTsKCmJ1ZmZlci5hcHBlbmQo
ImN1cnJlbnQgZGlyOiAiICsgU3lzdGVtLmdldFByb3BlcnR5KCJ1c2VyLmRpciIpKTsKYnVmZmVy
LmFwcGVuZChTeXN0ZW0ubGluZVNlcGFyYXRvcigpKTsKClN0cmluZyBmaWxlUGF0aCA9ICIvb3B0
L3NvZnR3YXJlYWcvSW50ZWdyYXRpb25TZXJ2ZXIvY29uZmlnL2FjbG1hcF9zbS5jbmYiOwoKdHJ5
IChCdWZmZXJlZFJlYWRlciByZWFkZXIgPSBuZXcgQnVmZmVyZWRSZWFkZXIobmV3IEZpbGVSZWFk
ZXIoZmlsZVBhdGgpKSkgewogICAgU3RyaW5nIGxpbmU7CiAgICB3aGlsZSAoKGxpbmUgPSByZWFk
ZXIucmVhZExpbmUoKSkgIT0gbnVsbCkgewogICAgICAgIGJ1ZmZlci5hcHBlbmQobGluZSk7CiAg
ICAgICAgYnVmZmVyLmFwcGVuZChTeXN0ZW0ubGluZVNlcGFyYXRvcigpKTsKICAgIH0KfSBjYXRj
aCAoSU9FeGNlcHRpb24gZSkgewogICAgdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZSk7Cn0K
Ci8vIFByaW50IHRoZSBjb250ZW50IG9mIHRoZSBmaWxlClN5c3RlbS5vdXQucHJpbnRsbihidWZm
ZXIudG9TdHJpbmcoKSk7CgovLyBwaXBlbGluZQpJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9
IHBpcGVsaW5lLmdldEN1cnNvcigpOwpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgIm91
dCIsIGJ1ZmZlci50b1N0cmluZygpICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTs=</value>
</Values>
