<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getAcls</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nQnVmZmVyIGJ1ZmZlciA9IG5ldyBTdHJpbmdCdWZmZXIoKTsKCmJ1ZmZlci5hcHBlbmQo
ImN1cnJlbnQgZGlyOiAiICsgU3lzdGVtLmdldFByb3BlcnR5KCJ1c2VyLmRpciIpKTsKYnVmZmVy
LmFwcGVuZChTeXN0ZW0ubGluZVNlcGFyYXRvcigpKTsKClN0cmluZyBmaWxlUGF0aCA9ICIvb3B0
L3NvZnR3YXJlYWcvSW50ZWdyYXRpb25TZXJ2ZXIvY29uZmlnL2FjbG1hcF9zbS5jb25mIjsKCnRy
eSAoQnVmZmVyZWRSZWFkZXIgcmVhZGVyID0gbmV3IEJ1ZmZlcmVkUmVhZGVyKG5ldyBGaWxlUmVh
ZGVyKGZpbGVQYXRoKSkpIHsKICAgIFN0cmluZyBsaW5lOwogICAgd2hpbGUgKChsaW5lID0gcmVh
ZGVyLnJlYWRMaW5lKCkpICE9IG51bGwpIHsKICAgICAgICBidWZmZXIuYXBwZW5kKGxpbmUpOwog
ICAgICAgIGJ1ZmZlci5hcHBlbmQoU3lzdGVtLmxpbmVTZXBhcmF0b3IoKSk7CiAgICB9Cn0gY2F0
Y2ggKElPRXhjZXB0aW9uIGUpIHsKICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9
CgovLyBQcmludCB0aGUgY29udGVudCBvZiB0aGUgZmlsZQpTeXN0ZW0ub3V0LnByaW50bG4oYnVm
ZmVyLnRvU3RyaW5nKCkpOwoKLy8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3Ig
PSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3IsICJv
dXQiLCBidWZmZXIudG9TdHJpbmcoKSApOwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7</value>
</Values>
